Repository portalarchitects/skysync-cli, pull requests merged in 2021-06, with the labels that each got.

#180 ACT-1163: Add PolicyTrackingGroup Resource
  src/sdk/resources/index.ts
  src/sdk/resources/policies.ts
  src/sdk/resources/policyTrackingGroups.ts
Labels: ready to merge

#182 ACT-1091: Add entity type dictionary/elements support
  src/sdk/client.ts
  src/sdk/models/entityTypes.ts
  src/sdk/resources/entityTypeDictionaries.ts
  src/sdk/resources/entityTypeDictionaryElements.ts
  src/sdk/resources/entityTypes.ts
  src/sdk/resources/index.ts
Labels: ready to merge

#185 ACT-1178 | adding entity type validators resource
  src/sdk/client.ts
  src/sdk/models/entityTypes.ts
  src/sdk/resources/entityTypeValidators.ts
  src/sdk/resources/index.ts
Labels: needs review

#187 CL99-63 | List users not filtering by active
  src/commands/users/list.ts
Labels: awaiting changes

#188 ACT-1167 - Add schema support to policies and entity types
  src/sdk/http/http-client.test.ts
  src/sdk/http/http-client.ts
  src/sdk/models/index.ts
  src/sdk/models/metadataSchema.ts
  src/sdk/resources/entityTypes.ts
  src/sdk/resources/policies.ts
Labels: ready to merge

#189 ACT-1524 | Add entity type assignment resources
  src/sdk/models/entityTypes.ts
  src/sdk/resources/policies.ts
  src/sdk/resources/policyTrackingGroups.ts
Labels: ready to merge

#190 ACT-1524-b | Updating Entity Type Assignment Endpoints from Patch to Post
  src/sdk/resources/policies.ts
  src/sdk/resources/policyTrackingGroups.ts
Labels: ready to merge

#192 ACT-1392: Add CSV file import method for keywords
  src/sdk/resources/entityTypeDictionaryElements.ts
Labels: ready to merge

#191 ACT-1169 | UI | Policy Editor | Allow managing list of actions
  src/sdk/client.ts
  src/sdk/models/policies.ts
  src/sdk/resources/index.ts
  src/sdk/resources/policyActionTypes.ts
Labels: ready to merge
