Repository portalarchitects/skysync-cli, pull requests merged in 2021-10, with the labels that each got.

#227 Sf-7915 | Unsupported file names, broken into separate functions | Truncation toggle
  src/sdk/models/transfers.ts
Labels: needs review, ready to merge

#228 ACT-965: Fix singular names for action types resource
  src/sdk/resources/policyActionTypes.ts
Labels: needs review

#231 SF 7794 | changes to allow bandwidth throttling configuration in the UI
  src/commands/performance/bandwidth_throttle.ts
  src/commands/performance/bandwidth_throttle/show.ts
  src/commands/performance/bandwidth_throttle/update.ts
  src/commands/performance/bandwidth_throttle/util.ts
  src/sdk/models/performance.ts
  src/sdk/resources/resource.test.ts
Labels: ready to merge
