Repository portalarchitects/skysync-cli, pull requests merged in 2022-02, with the labels that each got.

#247 ACT-2445 | Add link from backend to determine enabled state of Delete option.
  src/sdk/models/entityTypes.ts
Labels: needs review

#246 ACT-2086 | Add removeDataSource to policies resource
  src/sdk/resources/policies.ts
Labels: needs review, awaiting question

#248 ACT-3072 | Added threshold to MetadataPropertyFilter
  src/sdk/models/metadataFilters.ts
Labels: ready to merge
